-- AlterTable
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "vertexEngineId" TEXT;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "aiAppType" TEXT DEFAULT 'search_docs';
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "dataSourceType" TEXT DEFAULT 'none';
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "websiteUri" TEXT;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "gcsUri" TEXT;
